# build

FROM node:16.14.0-alpine AS build

ENV NODE_ENV "production"

COPY . /app
WORKDIR /app

#RUN npm install -D tailwindcss postcss autoprefixer
RUN npm install
RUN npm run build


# serve: https://hub.docker.com/_/nginx

FROM nginx:latest as serve

#COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx-default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/build /var/www/html

EXPOSE 80